unit udmEstruturaBancoRotina;

interface

uses
  System.SysUtils, System.Classes, Data.DB, MemDS, DBAccess, Uni;

type
    TdmEstruturaBancoRotina = class(TDataModule)
    I9APLICVERBA_CREATE: TUniQuery;
    I9_GERAVERBA_CREATE: TUniQuery;
    I9CONFIGUSUARIO_CREATE: TUniQuery;
    I9PARAMETROS_CREATE: TUniQuery;
    I9LISTAPRECIFICACAO_CREATE: TUniQuery;
    PKG_I9UTILITARIO_CABECALHO_CREATE: TUniQuery;
    PKG_I9UTILITARIO_CORPO_CREATE: TUniQuery;
    JOB_REPLICAR_OFERTA: TUniQuery;
    PRC_I9GERARANKING: TUniQuery;
    JOB_GERARANKING: TUniQuery;
    TABLE_I9_I9CONFIGVERBAOFERTA: TUniQuery;
    TABLE_I9CONFIGGRID: TUniQuery;
    TRG_PCPEDI_I9ATACVAREJO: TUniQuery;
    I9GERAVERBA_GENERICO: TUniQuery;
    TABLE_I9EXPORTEXCEL: TUniQuery;
    PRC_I9ATACVAREJO: TUniQuery;
    JOB_I9ATACVAREJO: TUniQuery;
    TABLE_I9CLIATACADOCRM: TUniQuery;
    SQL_CONSULTAS_CRM: TUniQuery;
    TRG_PCPEDC_I9CAMPANHACRM: TUniQuery;
    I9TABLOIDE_CREATE: TUniQuery;
    I9LOGALTERACAO_CREATE: TUniQuery;
    TRG_PCEMBALAGEM_I9LOGALTERACAO: TUniQuery;
    TRG_MARGENS_I9LOGALTERACAO: TUniQuery;
    TRG_PCEST_I9LOGALTERACAO: TUniQuery;
    TABLE_I9CAMPANHACRM: TUniQuery;
    TABLE_I9GRUPOCRMC: TUniQuery;
    TABLE_I9GRUPOCRMI: TUniQuery;
    TABLE_I9CAMPANHACRMGRUPOS: TUniQuery;
    PRC_I9INCLUIRCLIENTECRM: TUniQuery;
    SOMENTENUMERO: TUniQuery;
    TRG_I9_CRMPRODFIDELIDADE: TUniQuery;
    PKG_I9CLUBECRM_HEAD: TUniQuery;
    PKG_I9CLUBECRM_BODY: TUniQuery;
    JOB_I9_ATUALIZAR_ETIQUETAS: TUniQuery;
    JOB_I9_ATUALIZAR_PRECOVENDA: TUniQuery;
    TABLE_I9GRUPOFILIALC: TUniQuery;
    TABLE_I9GRUPOFILIALI: TUniQuery;
    TRG_PCPROMC_I9CAMPANHACRM: TUniQuery;
    TABLE_I9CLASSIFICMERC: TUniQuery;
    TABLE_I9CONFIGVERBACRM: TUniQuery;
    TABLE_I9CONCORRENTE: TUniQuery;
    TABLE_I9GRUPOFILIALCONC: TUniQuery;
    TABLE_I9PESQUISACONCORRENTE: TUniQuery;
    TABLE_I9LOGROTINA: TUniQuery;
    TABLE_I9CLUSTERCONCORRENTE: TUniQuery;
    TABLE_I9FILIALCONCORRENTE: TUniQuery;
    IS_NUMBER: TUniQuery;
    TABLE_I9CONTROLEINTEGRACAO: TUniQuery;
    TRG_I9_RECALCULAR_PRECOEMB: TUniQuery;
    TRG_PCEMBALAGEM_I9CAMPANHACRM: TUniQuery;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  dmEstruturaBancoRotina: TdmEstruturaBancoRotina;

implementation

{%CLASSGROUP 'Vcl.Controls.TControl'}

{$R *.dfm}

end.
